### ISSUE TITLE
Frequent permissions error

### ISSUE THREAD

**Issue by lincoln-harris** [wfondrie/ppx#12] opened 2021-09-01 20:13 UTC
Just so you know I'm seeing this error pretty frequently when I run `ppx.find_project()`:

```
error_perm: 550 Failed to change directory.
```

Usually its not a problem -- I can rerun the command a couple times and it ultimately works fine, but I figured I'd put it on your radar.

**Comment by wfondrie** [comment] 2021-09-01 20:25
That error typically indicates that you're trying to access a private project, for which you do not have permissions.

Can you provide some context on when this is happening?

**Comment by lincoln-harris** [comment] 2021-09-02 18:37
Sure, when I run:
```
proj = ppx.find_project("PXD010709", local="./PXD010709")
proj.remote_files()
```
I see the permissions error. But then I try back again a few minutes later and everything works fine, no errors.

**Comment by wfondrie** [comment] 2021-09-02 21:38
Can you post the full error you get next time it happens? I need a little more information to track down the cause. It's possible that this might be a temporary thing, because PRIDE was working on their servers recently:
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Due to some issues in our infrastructure, we cannot process any data submissions at the moment, or make datasets publicly available either. We apologize for the inconvenience and are working to try to get this solved asap. We will be reporting any updates. Apologies again</p>&mdash; PRIDE at EBI (@pride_ebi) <a href="https://twitter.com/pride_ebi/status/1433012452128661507?ref_src=twsrc%5Etfw">September 1, 2021</a></blockquote>

**Comment by lincoln-harris** [comment] 2021-09-06 23:37
```
error_perm                                Traceback (most recent call last)
<ipython-input-9-b85e8525005b> in <module>
      1 proj = ppx.find_project("PXD009905", local="./PXD009905")
----> 2 proj.remote_files()

~/miniconda3/envs/ms-impute/lib/python3.7/site-packages/ppx/project.py in remote_files(self, glob)
    145         """
    146         if self.fetch or self._remote_files is None:
--> 147             self._remote_files = self._parser.files
    148 
    149         if glob is not None:

~/miniconda3/envs/ms-impute/lib/python3.7/site-packages/ppx/ftp.py in files(self)
    140         """List the files form the FTP connection"""
    141         if self._files is None:
--> 142             self._get_files()
    143 
    144         return self._files

~/miniconda3/envs/ms-impute/lib/python3.7/site-packages/ppx/ftp.py in _get_files(self)
     66         with FTP(self.server) as repo:
     67             repo.login()
---> 68             repo.cwd(self.path)
     69             self._files, self._dirs = self._parse_files(repo)
     70             self._depth = 0

~/miniconda3/envs/ms-impute/lib/python3.7/ftplib.py in cwd(self, dirname)
    629             dirname = '.'  # does nothing, but could return error
    630         cmd = 'CWD ' + dirname
--> 631         return self.voidcmd(cmd)
    632 
    633     def size(self, filename):

~/miniconda3/envs/ms-impute/lib/python3.7/ftplib.py in voidcmd(self, cmd)
    276         """Send a command and expect a response beginning with '2'."""
    277         self.putcmd(cmd)
--> 278         return self.voidresp()
    279 
    280     def sendport(self, host, port):

~/miniconda3/envs/ms-impute/lib/python3.7/ftplib.py in voidresp(self)
    249     def voidresp(self):
    250         """Expect a response beginning with '2'."""
--> 251         resp = self.getresp()
    252         if resp[:1] != '2':
    253             raise error_reply(resp)

~/miniconda3/envs/ms-impute/lib/python3.7/ftplib.py in getresp(self)
    244             raise error_temp(resp)
    245         if c == '5':
--> 246             raise error_perm(resp)
    247         raise error_proto(resp)
    248 

error_perm: 550 Failed to change directory.
```

**Comment by wfondrie** [comment] 2021-09-07 17:01
Thanks! I'm seeing this same issue running the unit tests now. I think it may be a problem on PRIDE's end---I don't see the same issue using MassIVE projects---but I'm looking into it. It looks like PRIDE is still having internal issues, but I don't know if these affect their FTP server:
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Unfortunately, we continue in the same situation than last Wednesday. We are receiving the data submissions from all our users but we cannot process them. We cannot make data public either. We would really like to apologize for this. We are doing our best to get this solved asap.</p>&mdash; PRIDE at EBI (@pride_ebi) <a href="https://twitter.com/pride_ebi/status/1434810677990985730?ref_src=twsrc%5Etfw">September 6, 2021</a></blockquote>

**Comment by bittremieux** [comment] 2021-09-07 17:10
Yes, Ron Beavis reported on Twitter as well that he had issues browsing the PRIDE FTP servers, so it's very likely related to that.

**Comment by wfondrie** [comment] 2021-09-14 19:24
This should be resolved in the latest release. @lincoln-harris, if you still run into this error after updating to version 1.2.0, please re-open this issue!

**Closed by wfondrie** 2021-09-14 19:24 UTC
